<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2016/08/01 11:24:00

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=jobeet',
  'username' => 'root',
  'password' => 'YanivSymfony1.4',
  'name' => 'doctrine',
)),);
